### ISSUE TITLE
(JS-D007) Bad usage of `RegExp#exec` and `String#match`

### ISSUE THREAD

**Issue by vkhangstack** [vkhangstack/url-shortener#1]
## Description
`RegExp#exec` and `String#match` are used when we need matches, but it is unnecessary to use when we just want to check if a matching pattern is present in the given string. So, it can cost more in performance of the application.

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/vkhangstack/url-shortener/issue/JS-D007/occurrences/](https://deepsource.io/gh/vkhangstack/url-shortener/issue/JS-D007/occurrences/)

**Comment by maruthimohan** [comment]
@vkhangstack can I work on this? and also could you consider the PR for the Hacktoberfest?

**Comment by vkhangstack** [comment]
I am so happy about that

**Comment by maruthimohan** [comment]
Thank you for letting me work on this @vkhangstack ! I am new to open-source projects and this was a good introduction.

**Comment by vkhangstack** [comment]
Thank you @maruthimohan
